# Setup
title:               Blog
tagline:             ''
description:         'lectinua의 블로그'
url:                 'https://lectinua.github.io'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              lectinua
  email:             lectinua@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
google_analytics_id: UA-180775569-1
